# Generated by Django 4.2 on 2023-05-14 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='User',
        ),
        migrations.AlterField(
            model_name='subject',
            name='SubjectName',
            field=models.CharField(max_length=120, verbose_name='Subject Name'),
        ),
        migrations.CreateModel(
            name='myUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Student Name')),
                ('barcode', models.CharField(max_length=120, verbose_name='Barcode')),
                ('User', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.myuser'),
        ),
    ]
