# Generated by Django 4.2 on 2023-05-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_student_remove_subject_user_delete_myuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='TimeRemaining',
            field=models.DateTimeField(verbose_name='Deadline'),
        ),
    ]
