# Generated by Django 4.2 on 2023-05-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_subject_timeremaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Name',
            field=models.CharField(max_length=120, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='TimeRemaining',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Deadline'),
        ),
    ]
