# Generated by Django 4.2 on 2023-05-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_subject_name_alter_subject_timeremaining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='TimeRemaining',
            field=models.DateTimeField(verbose_name='Deadline'),
        ),
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Club name')),
                ('description', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('members', models.ManyToManyField(blank=True, to='events.student')),
            ],
        ),
    ]
