# Generated by Django 4.2 on 2023-05-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_rename_clubs_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
