# Generated by Django 4.2 on 2023-05-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_club_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Club name')),
                ('introduction', models.TextField(blank=True)),
                ('studytips', models.TextField(blank=True)),
                ('resourses', models.TextField(blank=True)),
                ('videoresources', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('videolinks', models.URLField(max_length=120, verbose_name='Website Address')),
            ],
        ),
    ]
