# Generated by Django 4.2 on 2023-05-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Course name')),
                ('links', models.URLField(max_length=120, verbose_name='Website Address')),
                ('status', models.CharField(choices=[('Textbooks', 'Textbooks'), ('Online Courses', 'Online Courses'), ('Websites and Blogs', 'Websites and Blogs'), ('Math Forums', 'Math Forums'), ('YouTube Channels', 'YouTube Channels'), ('MIT OpenCourseWare', 'MIT OpenCourseWare')], max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='videolinks',
        ),
        migrations.RemoveField(
            model_name='course',
            name='videoresources',
        ),
        migrations.RemoveField(
            model_name='course',
            name='resourses',
        ),
        migrations.AddField(
            model_name='course',
            name='resourses',
            field=models.ManyToManyField(blank=True, to='events.resource'),
        ),
    ]
