# Generated by Django 4.2 on 2023-05-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_resource_remove_course_videolinks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videoresource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Resource name')),
                ('links', models.URLField(max_length=120, verbose_name='Website Address')),
                ('status', models.CharField(choices=[('YouTube Channels', 'YouTube Channels'), ('MIT OpenCourseWare', 'MIT OpenCourseWare')], max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='conclusion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Resource name'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='status',
            field=models.CharField(choices=[('Textbooks', 'Textbooks'), ('Online Courses', 'Online Courses'), ('Websites and Blogs', 'Websites and Blogs'), ('Math Forums', 'Math Forums')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='vidoeresourses',
            field=models.ManyToManyField(blank=True, to='events.videoresource'),
        ),
    ]
