# Generated by Django 4.2 on 2023-05-31 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_course_course_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='resourses',
            new_name='resources',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='vidoeresourses',
            new_name='vidoeresources',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='links',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='videoresource',
            old_name='links',
            new_name='link',
        ),
    ]
