# Generated by Django 4.2 on 2023-05-31 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_rename_resourses_course_resources_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='vidoeresources',
            new_name='videoresources',
        ),
    ]
