# Generated by Django 4.2 on 2023-06-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_rename_vidoeresources_course_videoresources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='Name',
        ),
        migrations.AddField(
            model_name='subject',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
