# Generated by Django 4.2 on 2023-06-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_remove_subject_name_subject_data_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(max_length=120, null=True, verbose_name='Student Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.CharField(max_length=120, null=True, verbose_name='Student Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='student',
            name='surname',
            field=models.CharField(max_length=120, null=True, verbose_name='Student Surname'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Course name'),
        ),
    ]
