# Generated by Django 4.2 on 2023-06-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_student_city_student_country_student_profile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='barcode',
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(max_length=120, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.CharField(max_length=120, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile1.png', null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(max_length=120, null=True, verbose_name='Surname'),
        ),
    ]
